/**
 * Project copy / i18n keys.
 * All user-facing strings live here so Amharic can be layered later.
 */
export const COPY = {
  app: {
    name: "RentFlow",
    tagline: "Addis Rental Management",
  },
  nav: {
    dashboard: "Dashboard",
    buildings: "Buildings",
    offices: "Offices",
    tenants: "Tenants",
    leases: "Leases",
    payments: "Payments",
    invoices: "Invoices",
    maintenance: "Maintenance",
    notifications: "Notifications",
    reports: "Reports",
    settings: "Settings",
  },
  topbar: {
    search: "Search tenants, leases, invoices…",
    signedInAs: "Signed in as",
    settings: "Settings",
    notifications: "Notifications",
    signOut: "Sign out",
  },
  sidebar: {
    demoTag: "Demo Workspace",
    demoHint: "Mock data is stored locally. Use Settings → Reset to reseed.",
  },
  login: {
    headline: "Manage every Addis property, every lease, every Birr.",
    subheadline:
      "Buildings, offices, tenants, leases, payments, and invoices — built for the speed of the Bole office.",
    copyright: "RentFlow Demo. Built for Addis Ababa.",
    welcomeTitle: "Welcome back",
    welcomeSubtitle: "Sign in to continue to your workspace",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot?",
    signIn: "Sign in",
    signingIn: "Signing in…",
    welcomeBack: "Welcome back!",
    demoTitle: "Demo mode",
    demoHint: "Any email and password work. The demo account is pre-filled.",
  },
  dashboard: {
    title: "Dashboard",
    description: "A live view of your Addis portfolio — leases, revenue, occupancy, and what needs attention today.",
    metrics: {
      occupancy: "Occupancy rate",
      activeLeases: "Active leases",
      overduePayments: "Overdue payments",
      monthlyRevenue: "Revenue (last 30 days)",
      activeTenants: "Active tenants",
      expiringSoon: "Expiring in 60 days",
      collectionRate: "Collection rate (this month)",
      vacantOffices: "Vacant offices",
    },
    sections: {
      revenueTrend: "Revenue trend (12 months)",
      recentPayments: "Recent payments",
      upcomingRenewals: "Upcoming renewals",
      expiringLeases: "Expiring leases (60 days)",
      occupancyByBuilding: "Occupancy by building",
      paymentStatusMix: "Payment status mix",
    },
    empty: {
      recentPayments: "No payments yet",
      expiringLeases: "No leases expiring soon",
    },
  },
  buildings: {
    title: "Buildings",
    description: "Your Addis property portfolio. Click a building to see floors, offices, and current tenants.",
    addBuilding: "Add building",
    editBuilding: "Edit building",
    deleteBuilding: "Delete building",
    deleteConfirm: "Delete this building? Floors and offices inside it will be detached.",
    fields: {
      name: "Name",
      address: "Address",
      district: "District",
      totalFloors: "Total floors",
      photoSeed: "Photo seed",
      notes: "Notes",
    },
    detail: {
      title: "Building details",
      floors: "Floors",
      offices: "Offices",
      occupancy: "Occupancy",
      monthlyRevenue: "Monthly revenue",
      backToBuildings: "Back to buildings",
    },
    empty: {
      title: "No buildings yet",
      description: "Add your first building to start tracking offices and tenants.",
    },
  },
  offices: {
    title: "Offices",
    description: "Every office across every building. Filter by status to see what's vacant.",
    addOffice: "Add office",
    fields: {
      building: "Building",
      floor: "Floor",
      number: "Office number",
      area: "Area (m²)",
      monthlyRate: "Monthly rate (ETB)",
      status: "Status",
    },
    empty: {
      title: "No offices",
      description: "Add an office to a building to track its status and rent.",
    },
  },
  tenants: {
    title: "Tenants",
    description: "All people and companies leasing your spaces.",
    addTenant: "Add tenant",
    editTenant: "Edit tenant",
    deleteTenant: "Delete tenant",
    deleteConfirm: "Delete this tenant? Their leases will be unlinked.",
    fields: {
      fullName: "Full name",
      company: "Company",
      phone: "Phone",
      email: "Email",
      status: "Status",
      moveInDate: "Move-in date",
      notes: "Notes",
    },
    detail: {
      title: "Tenant details",
      leases: "Leases",
      payments: "Payments",
      contact: "Contact",
      moveInDate: "Move-in date",
      backToTenants: "Back to tenants",
      noLeases: "No leases yet for this tenant.",
      noPayments: "No payments yet for this tenant.",
    },
    empty: {
      title: "No tenants",
      description: "Add your first tenant to get started.",
    },
  },
  leases: {
    title: "Leases",
    description: "Active, expiring, and expired leases. Renewals inside 60 days are highlighted.",
    addLease: "Add lease",
    fields: {
      tenant: "Tenant",
      office: "Office",
      startDate: "Start date",
      endDate: "End date",
      monthlyRent: "Monthly rent (ETB)",
      depositAmount: "Deposit (ETB)",
      status: "Status",
    },
    detail: {
      title: "Lease details",
      tenant: "Tenant",
      office: "Office",
      period: "Period",
      monthlyRent: "Monthly rent",
      deposit: "Deposit",
      payments: "Payments",
      backToLeases: "Back to leases",
    },
    empty: {
      title: "No leases",
      description: "Create a lease to connect a tenant with an office.",
    },
  },
  payments: {
    title: "Payments",
    description: "Rent payments, statuses, and overdue tracking.",
    addPayment: "Record payment",
    markPaid: "Mark as paid",
    fields: {
      lease: "Lease",
      tenant: "Tenant",
      periodMonth: "Period (month)",
      amount: "Amount (ETB)",
      dueDate: "Due date",
      paidDate: "Paid date",
      method: "Method",
      status: "Status",
      reference: "Reference",
    },
    empty: {
      title: "No payments",
      description: "Payments will appear here as leases are billed.",
    },
  },
  invoices: {
    title: "Invoices",
    description: "Generated invoices. Click to view, print, or mark paid.",
    addInvoice: "Create invoice",
    fields: {
      invoiceNumber: "Invoice #",
      tenant: "Tenant",
      issueDate: "Issue date",
      dueDate: "Due date",
      lineItems: "Line items",
      vat: "VAT",
      total: "Total",
    },
    detail: {
      title: "Invoice",
      billTo: "Bill to",
      issueDate: "Issue date",
      dueDate: "Due date",
      description: "Description",
      amount: "Amount",
      subtotal: "Subtotal",
      vat: "VAT (15%)",
      total: "Total",
      print: "Print invoice",
      downloadPdf: "Download PDF",
      backToInvoices: "Back to invoices",
      status: "Status",
    },
    empty: {
      title: "No invoices",
      description: "Create your first invoice to bill a tenant.",
    },
  },
  maintenance: {
    title: "Maintenance",
    description: "Open maintenance requests across your portfolio.",
    addRequest: "New request",
    fields: {
      office: "Office",
      tenant: "Tenant",
      title: "Title",
      description: "Description",
      priority: "Priority",
      status: "Status",
    },
    empty: {
      title: "No maintenance requests",
      description: "All clear. New requests will appear here.",
    },
  },
  notifications: {
    title: "Notifications",
    description: "Lease expiry, overdue payments, and system events.",
    markAllRead: "Mark all as read",
    empty: {
      title: "All caught up",
      description: "No new notifications.",
    },
  },
  reports: {
    title: "Reports",
    description: "Aggregated views across your portfolio.",
    sections: {
      occupancy: "Occupancy by building",
      revenue: "Revenue trend (12 months)",
      upcoming: "Upcoming renewals (60 days)",
      overdue: "Overdue payments",
    },
  },
  settings: {
    title: "Settings",
    description: "Organization profile, currency, and demo controls.",
    sections: {
      orgProfile: "Organization profile",
      preferences: "Preferences",
      dangerZone: "Demo controls",
    },
    fields: {
      orgName: "Organization name",
      adminName: "Admin name",
      adminEmail: "Admin email",
      address: "Address",
      phone: "Phone",
      vatRate: "VAT rate",
      currency: "Currency",
    },
    actions: {
      save: "Save changes",
      resetSeed: "Reset to seed data",
      resetConfirm: "This will erase all local data and reload with seed values. Continue?",
    },
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    back: "Back",
    loading: "Loading…",
    noResults: "No results",
    tryAgain: "Try again",
    actions: "Actions",
    none: "None",
    yes: "Yes",
    no: "No",
    all: "All",
    status: "Status",
    search: "Search…",
    optional: "(optional)",
    created: "Created",
    updated: "Updated",
    showing: "Showing",
    of: "of",
  },
} as const;
